-- Migration 0001: Initial schema
-- Source of truth: docs/campaign-state-schema.md
-- DO NOT edit this file after it ships. Add new migrations instead.

PRAGMA journal_mode = WAL;
PRAGMA foreign_keys = ON;

-- =========================================================================
-- 1. Metadata & sessions
-- =========================================================================

CREATE TABLE campaign (
    id              INTEGER PRIMARY KEY CHECK (id = 1),
    name            TEXT    NOT NULL,
    system          TEXT    NOT NULL DEFAULT '5e-2024',
    schema_version  INTEGER NOT NULL DEFAULT 1,
    created_at      TEXT    NOT NULL
);

CREATE TABLE sessions (
    id              INTEGER PRIMARY KEY,
    number          INTEGER UNIQUE NOT NULL,
    played_at       TEXT,
    ended_at        TEXT,
    summary_file    TEXT,
    recap_file      TEXT,
    key_events_json TEXT
);

-- =========================================================================
-- 2. Player characters
-- =========================================================================

CREATE TABLE pcs (
    id                INTEGER PRIMARY KEY,
    name              TEXT UNIQUE NOT NULL,
    player_name       TEXT,
    class             TEXT,
    subclass          TEXT,
    level             INTEGER NOT NULL,
    max_hp            INTEGER NOT NULL,
    current_hp        INTEGER NOT NULL,
    temp_hp           INTEGER NOT NULL DEFAULT 0,
    ac                INTEGER NOT NULL,
    initiative_bonus  INTEGER NOT NULL DEFAULT 0,
    speed_walk        INTEGER NOT NULL DEFAULT 30,
    speed_fly         INTEGER          DEFAULT 0,
    speed_swim        INTEGER          DEFAULT 0,
    senses_json       TEXT,
    saves_json        TEXT,
    spell_slots_json  TEXT,
    resistances_json  TEXT,
    immunities_json   TEXT,
    conditions_json   TEXT,
    dossier_file      TEXT,
    voice_profile     TEXT,
    active            INTEGER NOT NULL DEFAULT 1,
    notes             TEXT
);

-- =========================================================================
-- 3. NPCs
-- =========================================================================

CREATE TABLE npcs (
    id                  INTEGER PRIMARY KEY,
    name                TEXT UNIQUE NOT NULL,
    role                TEXT,
    status              TEXT NOT NULL DEFAULT 'alive',
    current_location    TEXT,
    faction             TEXT,
    voice_profile       TEXT,
    dossier_file        TEXT,
    introduced_session  INTEGER,
    notes_summary       TEXT
);

-- =========================================================================
-- 4. Combat
-- =========================================================================

CREATE TABLE combats (
    id                  INTEGER PRIMARY KEY,
    session_id          INTEGER NOT NULL,
    started_at          TEXT NOT NULL,
    ended_at            TEXT,
    outcome             TEXT,
    initiative_json     TEXT,
    current_turn        INTEGER NOT NULL DEFAULT 0,
    round_number        INTEGER NOT NULL DEFAULT 1,
    intensity           TEXT NOT NULL DEFAULT 'normal',
    difficulty          TEXT,
    narrative_context   TEXT,
    FOREIGN KEY (session_id) REFERENCES sessions(id)
);

CREATE TABLE npc_instances (
    id              INTEGER PRIMARY KEY,
    combat_id       INTEGER NOT NULL,
    npc_id          INTEGER,
    template_key    TEXT,
    display_name    TEXT NOT NULL,
    max_hp          INTEGER NOT NULL,
    current_hp      INTEGER NOT NULL,
    ac              INTEGER NOT NULL,
    conditions_json TEXT,
    map_token_id    TEXT,
    defeated        INTEGER NOT NULL DEFAULT 0,
    FOREIGN KEY (combat_id) REFERENCES combats(id),
    FOREIGN KEY (npc_id)    REFERENCES npcs(id)
);

-- =========================================================================
-- 5. World
-- =========================================================================

CREATE TABLE locations (
    id                  INTEGER PRIMARY KEY,
    name                TEXT UNIQUE NOT NULL,
    type                TEXT,
    parent_id           INTEGER,
    status              TEXT NOT NULL DEFAULT 'unknown',
    dossier_file        TEXT,
    introduced_session  INTEGER,
    FOREIGN KEY (parent_id) REFERENCES locations(id)
);

CREATE TABLE factions (
    id              INTEGER PRIMARY KEY,
    name            TEXT UNIQUE NOT NULL,
    reputation      INTEGER NOT NULL DEFAULT 0,
    status          TEXT,
    dossier_file    TEXT
);

CREATE TABLE quests (
    id                  INTEGER PRIMARY KEY,
    title               TEXT NOT NULL,
    state               TEXT NOT NULL DEFAULT 'active',
    summary             TEXT,
    giver_npc_id        INTEGER,
    related_location_id INTEGER,
    introduced_session  INTEGER,
    resolved_session    INTEGER,
    notes_file          TEXT,
    FOREIGN KEY (giver_npc_id)        REFERENCES npcs(id),
    FOREIGN KEY (related_location_id) REFERENCES locations(id)
);

CREATE TABLE clock (
    id                  INTEGER PRIMARY KEY CHECK (id = 1),
    in_world_date       TEXT,
    time_of_day         TEXT,
    weather             TEXT,
    current_location_id INTEGER,
    party_state         TEXT,
    FOREIGN KEY (current_location_id) REFERENCES locations(id)
);

-- =========================================================================
-- 6. Inventory
-- =========================================================================

CREATE TABLE inventory (
    id          INTEGER PRIMARY KEY,
    owner_kind  TEXT    NOT NULL,
    owner_id    INTEGER,
    name        TEXT    NOT NULL,
    kind        TEXT,
    description TEXT,
    qty         INTEGER NOT NULL DEFAULT 1,
    notes       TEXT
);

-- =========================================================================
-- 7. Seeds & secrets
-- =========================================================================

CREATE TABLE seeds (
    id                  INTEGER PRIMARY KEY,
    text                TEXT NOT NULL,
    trigger_condition   TEXT,
    status              TEXT NOT NULL DEFAULT 'planted',
    visibility          TEXT NOT NULL DEFAULT 'public',
    planted_session     INTEGER,
    triggered_session   INTEGER
);

CREATE TABLE secrets (
    id                  INTEGER PRIMARY KEY,
    topic               TEXT,
    text                TEXT NOT NULL,
    related_npc_id      INTEGER,
    related_location_id INTEGER,
    status              TEXT NOT NULL DEFAULT 'hidden',
    added_session       INTEGER,
    FOREIGN KEY (related_npc_id)      REFERENCES npcs(id),
    FOREIGN KEY (related_location_id) REFERENCES locations(id)
);

-- =========================================================================
-- 8. Memory chunks + FTS5
-- =========================================================================

CREATE TABLE memory_chunks (
    id              INTEGER PRIMARY KEY,
    kind            TEXT NOT NULL,
    text            TEXT NOT NULL,
    source_file     TEXT,
    source_session  INTEGER,
    tags_json       TEXT,
    created_at      TEXT NOT NULL
);

CREATE VIRTUAL TABLE memory_chunks_fts USING fts5(
    text,
    content='memory_chunks',
    content_rowid='id'
);

-- Triggers to keep FTS index in sync with the content table
CREATE TRIGGER memory_chunks_ai AFTER INSERT ON memory_chunks BEGIN
    INSERT INTO memory_chunks_fts(rowid, text) VALUES (new.id, new.text);
END;

CREATE TRIGGER memory_chunks_ad AFTER DELETE ON memory_chunks BEGIN
    INSERT INTO memory_chunks_fts(memory_chunks_fts, rowid, text) VALUES('delete', old.id, old.text);
END;

CREATE TRIGGER memory_chunks_au AFTER UPDATE ON memory_chunks BEGIN
    INSERT INTO memory_chunks_fts(memory_chunks_fts, rowid, text) VALUES('delete', old.id, old.text);
    INSERT INTO memory_chunks_fts(rowid, text) VALUES (new.id, new.text);
END;

-- =========================================================================
-- 9. Event log
-- =========================================================================

CREATE TABLE events (
    id           INTEGER PRIMARY KEY,
    timestamp    TEXT NOT NULL,
    session_id   INTEGER,
    source       TEXT NOT NULL,
    type         TEXT NOT NULL,
    payload_json TEXT NOT NULL,
    reverted     INTEGER NOT NULL DEFAULT 0
);

CREATE INDEX events_session ON events(session_id);
CREATE INDEX events_type    ON events(type);
CREATE INDEX events_time    ON events(timestamp);

-- =========================================================================
-- 10. Schema version tracking
-- =========================================================================

CREATE TABLE schema_migrations (
    version     INTEGER PRIMARY KEY,
    applied_at  TEXT NOT NULL
);

INSERT INTO schema_migrations (version, applied_at) VALUES (1, datetime('now'));
